  - name: Add master as host
    local_action:
      module: add_host
      name: "{{ os_master.default_ip  }}" 
      groups: nodes, master
      ansible_ssh_private_key_file: "~/.ssh/id_rsa_{{ ssh_key }}"

  - name: Add nodes as hosts 
    local_action:
      module: add_host
      name: "{{ item.default_ip }}" 
      groups: nodes
      ansible_ssh_private_key_file: "~/.ssh/id_rsa_{{ ssh_key }}"
    with_items: '{{ os_nodes.results }}'

