# Doc at http://docs.ansible.com/ansible/cs_securitygroup_rule_module.html

# Rules to be added in the security group
  - name: SSH to instances
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ security_group_name }}"
     cidr: 195.65.181.75/32
     start_port: 22
     end_port: 22

  - name: Access to OpenShift console
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ security_group_name }}"
     cidr: 195.65.181.75/32
     start_port: 8443 
     end_port: 8443 
